apiVersion: apps/v1
kind: Deployment
metadata:
  name: loglens-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: loglens-backend
  template:
    metadata:
      labels:
        app: loglens-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: backend
          image: {{ .Values.image }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {{ toYaml .Values.resources | nindent 10 }}
