{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default "ingress-backend" .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                # service name created by this chart
                name: loglens-backend
                port:
                  number: {{ .Values.service.port }}
{{- end }}
