{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
stringData:
  GEMINI_API_KEY: {{ .Values.secret.data.GEMINI_API_KEY | quote }}
  DATABASE_URL: {{ .Values.secret.data.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.secret.data.REDIS_URL | quote }}
{{- end }}
