apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.stableName }}
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: loglens-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.canaryName }}
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: loglens-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: ClusterIP
