apiVersion: apps/v1
kind: Deployment
metadata:
  name: loglens-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: loglens-frontend
  template:
    metadata:
      labels:
        app: loglens-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image }}
          ports:
            - containerPort: 5173
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5173
            initialDelaySeconds: 15
            periodSeconds: 20
          resources: {{ toYaml .Values.resources | nindent 15 }}
      volumes:
        - name: nginx-config
          configMap:
            name: loglens-frontend-nginx-config
            items:
              - key: default.conf
                path: default.conf
