{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default "ingress-app1" .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.ingress.api.enabled }}
          - path: {{ .Values.ingress.api.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.api.service.name | quote }}
                port:
                  number: {{ .Values.ingress.api.service.port }}
          {{- end }}
          {{- if .Values.ingress.health.enabled }}
          - path: {{ .Values.ingress.health.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.health.service.name | quote }}
                port:
                  number: {{ .Values.ingress.health.service.port }}
          {{- end }}
          {{- if .Values.ingress.fixedResponse.enabled }}
          - path: {{ .Values.ingress.fixedResponse.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.fixedResponse.name | quote }}
                port:
                  name: use-annotation
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.frontend.service.name | quote }}
                port:
                  number: {{ .Values.ingress.frontend.service.port }}
{{- end }}
