pipeline {
    agent any

    options {
        disableConcurrentBuilds()
    }

    environment {
        APP_NAME        = "loglens-frontend"
        AWS_REGION      = "ap-south-1"
        AWS_ACCOUNT_ID  = "432995435807"
        ECR_REPO        = "cu-final/${APP_NAME}"
        REGISTRY        = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        ECR_URI         = "${REGISTRY}/${ECR_REPO}"
        APP_PATH        = "Application/frontend"
        HELM_PATH       = "Application/helm/frontend"
        GIT_REPO        = "https://github.com/zoro2024/CU-MCA-final-project.git"
        GIT_CREDENTIALS = "cu-final-akshit"
        ARGOCD_APP_NAME = "loglens-frontend"
        SONAR_SCANNER_HOME = tool 'prod-sonarqube'
    }

    parameters {

        choice(
            name: 'DEPLOY_TYPE',
            choices: ['Canary Rollout', 'Rollout Existing Tag'],
            description: 'Select deployment mode'
        )

        string(
            name: 'BRANCH_NAME',
            defaultValue: 'master',
            description: 'Git branch to build'
        )

        string(
            name: 'ROLL_OUT_TAG',
            defaultValue: '',
            description: 'Existing image tag for rollout'
        )
    }

    stages {

        stage('Checkout Code') {
            when {
                expression { params.DEPLOY_TYPE == 'Canary Rollout' }
            }

            steps {
                git(
                    url: "${GIT_REPO}",
                    credentialsId: "${GIT_CREDENTIALS}",
                    branch: "${params.BRANCH_NAME}"
                )
            }
        }

        stage('Set Image Variables') {
            steps {
                script {

                    if (params.DEPLOY_TYPE == 'Canary Rollout') {

                        def commitHash = sh(
                            script: "git rev-parse --short HEAD",
                            returnStdout: true
                        ).trim()

                        env.IMAGE_TAG = "${commitHash}-${BUILD_NUMBER}"

                    } else {

                        if (!params.ROLL_OUT_TAG?.trim()) {
                            error("ROLL_OUT_TAG is required for Rollout Existing Tag")
                        }

                        env.IMAGE_TAG = params.ROLL_OUT_TAG
                    }

                    env.IMAGE_NAME = "${ECR_URI}:${IMAGE_TAG}"

                    echo "Using Image: ${env.IMAGE_NAME}"
                }
            }
        }

        stage('Gitleaks Scan') {
            when {
                expression { params.DEPLOY_TYPE == 'Canary Rollout' }
            }

            steps {
                sh """
                    echo "Running Gitleaks scan..."

                    gitleaks detect \
                    --source . \
                    --report-format json \
                    --report-path gitleaks-report.json || true
                """
            }
        }

        stage('SonarQube Analysis') {
            when {
                expression { params.DEPLOY_TYPE == 'Canary Rollout' }
            }

            steps {
                withSonarQubeEnv('prod-sonarqube') {

                    dir("${APP_PATH}") {

                        sh """
                            export PATH=${SONAR_SCANNER_HOME}/bin:$PATH

                            sonar-scanner \
                              -Dsonar.projectKey=${APP_NAME} \
                              -Dsonar.projectName=${APP_NAME} \
                              -Dsonar.sources=. \
                              -Dsonar.host.url=$SONAR_HOST_URL \
                              -Dsonar.login=$SONAR_AUTH_TOKEN
                        """
                    }
                }
            }
        }

        stage('Login to AWS ECR') {
            when {
                expression { params.DEPLOY_TYPE == 'Canary Rollout' }
            }

            steps {
                sh """
                    aws ecr get-login-password --region ${AWS_REGION} | \
                    docker login --username AWS --password-stdin ${REGISTRY}
                """
            }
        }

        stage('Build Docker Image') {
            when {
                expression { params.DEPLOY_TYPE == 'Canary Rollout' }
            }

            steps {
                dir("${APP_PATH}") {
                    sh """
                        docker build -t ${IMAGE_NAME} .
                    """
                }
            }
        }

        stage('Trivy Scan (Report)') {
            when {
                expression { params.DEPLOY_TYPE == 'Canary Rollout' }
            }

            steps {
                sh """
                    echo "Downloading Trivy HTML template..."
                    wget -q https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

                    echo "Generating Trivy report..."
                    trivy image \
                    --format template \
                    --template "@html.tpl" \
                    -o trivy-report.html \
                    ${IMAGE_NAME}

                    rm -f html.tpl
                """
            }
        }

        stage('Push Docker Image') {
            when {
                expression { params.DEPLOY_TYPE == 'Canary Rollout' }
            }

            steps {
                sh """
                    docker push ${IMAGE_NAME}
                """
            }
        }

        stage('Update Helm Values') {

            steps {

                sh """
                    sed -i 's|tag:.*|tag: "${IMAGE_TAG}"|g' ${HELM_PATH}/values.yaml
                """

                withCredentials([
                    usernamePassword(
                        credentialsId: "${GIT_CREDENTIALS}",
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS'
                    )
                ]) {

                    sh """
                        git config user.name "Jenkins CI"
                        git config user.email "jenkins@cu-final"

                        git add ${HELM_PATH}/values.yaml
                        git commit -m "update ${APP_NAME} image tag to ${IMAGE_TAG}" || echo "No changes"

                        git remote set-url origin https://${USER}:${PASS}@github.com/zoro2024/CU-MCA-final-project.git
                        git push origin ${params.BRANCH_NAME}
                    """
                }
            }
        }

        stage('Sync ArgoCD Application') {

            steps {

                withCredentials([

                    string(credentialsId: 'ARGOCD_SERVER', variable: 'ARGOCD_SERVER'),
                    string(credentialsId: 'ARGO_USER', variable: 'ARGO_USER'),
                    string(credentialsId: 'ARGO_PASS', variable: 'ARGO_PASS'),

                    usernamePassword(
                        credentialsId: "${GIT_CREDENTIALS}",
                        usernameVariable: 'USER',
                        passwordVariable: 'PASS'
                    )
                ]) {

                    script {

                        try {

                            sh """
                                argocd login ${ARGOCD_SERVER} \
                                --username ${ARGO_USER} \
                                --password ${ARGO_PASS} \
                                --plaintext \
                                --grpc-web \
                                --skip-test-tls
                            """

                            sh """
                                argocd app sync ${ARGOCD_APP_NAME}
                            """

                            sh """
                                argocd app wait ${ARGOCD_APP_NAME} \
                                --health --sync --timeout 300
                            """

                            echo "Deployment successful"
                        }

                        catch (Exception e) {

                            echo "Deployment failed. Rolling back..."

                            sh """
                                git remote set-url origin https://${USER}:${PASS}@github.com/zoro2024/CU-MCA-final-project.git

                                LAST_COMMIT=\$(git rev-parse HEAD)

                                git revert --no-edit \$LAST_COMMIT
                                git push origin ${params.BRANCH_NAME}
                            """

                            sh """
                                argocd app sync ${ARGOCD_APP_NAME}
                                argocd app wait ${ARGOCD_APP_NAME} --health --sync --timeout 300
                            """

                            error("Deployment failed after rollback")
                        }
                    }
                }
            }
        }
    }

    post {

        success {
            echo "Deployment completed successfully with image: ${env.IMAGE_NAME}"
        }

        failure {
            echo "Pipeline failed"
        }

        always {

            script {
                echo "Archiving security reports..."

                archiveArtifacts artifacts: 'gitleaks-report.json', allowEmptyArchive: true
                archiveArtifacts artifacts: 'trivy-report.html', allowEmptyArchive: true
            }

            sh """
                docker rmi -f ${IMAGE_NAME} || true
            """

            cleanWs()
        }
    }
}
