---
apiVersion: v1
kind: Service
metadata:
  name: loglens-backend
  namespace: loglens
spec:
  type: ClusterIP
  selector:
    app: loglens-backend
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP