apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loglens-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/zoro2024/CU-MCA-final-project.git
    targetRevision: master
    path: Application/helm/frontend
    helm:
      releaseName: loglens-frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: loglens

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
