apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loglens-frontend-ingress
  namespace: loglens
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: shared-alb
    alb.ingress.kubernetes.io/load-balancer-name: shared-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/target-type: ip

spec:
  ingressClassName: alb

  rules:
  - host: loglens.dealshare.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loglens-frontend-stable
            port:
              number: 80