apiVersion: v1
kind: Service
metadata:
  name: loglens-frontend-stable
  namespace: loglens

spec:
  selector:
    app: loglens-frontend

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: loglens-frontend-canary
  namespace: loglens

spec:
  selector:
    app: loglens-frontend

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

  type: ClusterIP