namespace: loglens

replicaCount: 1

image:
  repository: 432995435807.dkr.ecr.ap-south-1.amazonaws.com/cu-final/loglens-frontend
  tag: "fd678f1-3"
  pullPolicy: IfNotPresent

service:
  stableName: loglens-frontend-stable
  canaryName: loglens-frontend-canary
  port: 80

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 65

ingress:
  host: loglens.dealshare.in
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: shared-alb
    alb.ingress.kubernetes.io/load-balancer-name: shared-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/target-type: ip

backend:
  serviceName: loglens-backend-stable

canary:
  steps:
  - setWeight: 40
  - pause:
      duration: "1m"
  - setWeight: 100

